In [8]:
# Fatemeh Makhloughi
# Machine Learning
# HW7 - SVM classifier for digits dataset
from sklearn.datasets import load_digits
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
import numpy as np

In [9]:
digits = load_digits()

In [10]:
x = digits.data
y = digits.target

In [13]:
type(x)

numpy.ndarray

In [11]:
np.shape(x)

(1797, 64)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
svc_classifier = SVC(kernel='linear', C=1)
svc_classifier.fit(x_train, y_train)

SVC(C=1, kernel='linear')

In [ ]:
print("Accuracy: %0.2f" % svc_classifier.score(x_test, y_test))

Accuracy: 0.98


In [ ]:
score = cross_val_score(svc_classifier, x, y, cv = 5)

In [ ]:
print("Mean accuracy: %0.2f with a standard deviation of %0.2f" % (score.mean(),score.std()))

Mean accuracy: 0.95 with a standard deviation of 0.02


In [ ]:
grid_parameters = {'C': [1,5, 10, 50, 100], 'gamma':[0.001, 0.01, 0.1, 1, 10],'kernel': ['rbf','linear']}
grid = GridSearchCV(SVC(),grid_parameters)
grid.fit(x_train,y_train)
print("Grid Best Result:",grid.best_params_)

Grid Best Result: {'C': 5, 'gamma': 0.001, 'kernel': 'rbf'}


In [ ]:
pred = grid.predict(x_test)

In [ ]:
print("accuracy =  %0.2f" % grid.score(x_test, y_test))

accuracy =  0.99


In [ ]:
print(confusion_matrix(y_test, pred))

[[33  0  0  0  0  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  0 33  0  1  0  0  0  0]
 [ 0  0  0  0 46  0  0  0  0  0]
 [ 0  0  0  0  0 46  1  0  0  0]
 [ 0  0  0  0  0  0 35  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  0  0  0  0  0  0  0 30  0]
 [ 0  0  0  0  0  0  0  1  0 39]]
